import "../styles/globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "../styles/redStyle.scss";

import MyNav from "../components/MyNav";
import Head from "next/head";

import Context from "../utilities/Context";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Your Next Favorite Games</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossOrigin="anonymous"
        />
      </Head>
      <Context>
        <MyNav />
        <Component {...pageProps} />
      </Context>
    </>
  );
}

export default MyApp;
